import { ValidSkills } from "./constants";

export interface CareerExperienceInterface {
  id: string;
  position: string;
  company: string;
  location: string;
  startDate: Date;
  endDate: Date | "Present";
  description: string[];
  achievements: string[];
  skills: ValidSkills[];
  companyUrl?: string;
  logo?: string;
}

export const careerExperiences: CareerExperienceInterface[] = [
  {
    id: "cyphershield",
    position: "Co-Founder",
    company: "CypherShield",
    location: "Remote",
    startDate: new Date("2025-01-01"),
    endDate: "Present",
    description: [
      "Co-founded an AI-powered cybersecurity startup focused on consensus-driven AI decision support and intelligence platforms.",
      "Led development of CypherShield Accord, an industry-first AI consensus engine that orchestrates specialized AI sub-experts across domains.",
      "Built modular AI systems using Small Language Models (SLMs) and Large Language Models (LLMs) for enhanced security and clinical precision.",
      "Developed backend services using NestJS, Python, and FastAPI for real-time AI orchestration and decision-making.",
      "Created Cypher Email Shield, an AI solution that blocks phishing attacks using multi-layered, consensus-driven approaches.",
      "Implemented zero-trust security framework with blockchain-backed audit trails for compliance and privacy.",
      "Built scalable infrastructure supporting healthcare, finance, aerospace, and cybersecurity use cases.",
    ],
    achievements: [
      "Successfully co-founded CypherShield, pioneering consensus-driven AI technology for critical decision-making across industries.",
      "Led development of CypherShield Accord, the first AI consensus engine that combines multiple specialized AI models for superior accuracy and transparency.",
      "Built modular AI ecosystem using SLMs and LLMs, achieving 5x improvement in large-scale agent networks through optimized communication protocols.",
      "Developed Cypher Email Shield using advanced AI consensus to block phishing attacks before they reach inboxes.",
      "Implemented zero-trust security framework with blockchain audit trails, ensuring compliance for healthcare, finance, and critical infrastructure.",
      "Created scalable infrastructure supporting real-time medical diagnostics, pharmaceutical research, and cybersecurity operations.",
      "Established strategic partnerships and raised funding for innovative AI solutions that bridge traditional cybersecurity with advanced AI capabilities.",
    ],
    skills: [
      "Nest.js",
      "Python",
      "FastAPI",
      "AI/ML",
      "Machine Learning",
      "Next.js",
      "Cybersecurity",
      "Blockchain",
      "Microservices",
      "Team Leadership",
      "Business Development",
    ],
    companyUrl: "https://cyphershield.io",
    logo: "/experience/cyphershield/logo.png",
  },
  {
    id: "secuvy",
    position: "Senior Software Developer",
    company: "Secuvy",
    location: "Hyderabad, India",
    startDate: new Date("2023-09-01"),
    endDate: "Present",
    description: [
      "Leading backend development initiatives focused on data security and privacy, including building POCs.",
      "Built and maintained core backend services using Node.js (TypeScript), AWS Lambda and n8n in a microservices architecture.",
      "Integrated Redis (BullQ), and RabbitMQ for queue-based async processing and inter-service communication.",
      "Set up CI/CD pipelines using GitLab, deploying services on AWS EKS (Kubernetes) with automated testing and rollback.",
      "Implemented monitoring using Prometheus + Grafana, and centralized logging via the ELK Stack.",
      "Collaborated with the AI team to integrate privacy-preserving machine learning models.",
      "Mentored junior developers and participated in architecture planning, sprint cycles, and Agile ceremonies.",
    ],
    achievements: [
      "Led backend development initiatives focused on data security and privacy, including building POCs for innovative solutions.",
      "Built and maintained core backend services using Node.js (TypeScript), AWS Lambda and n8n in a microservices architecture, ensuring scalability and maintainability.",
      "Integrated Redis (BullQ), and RabbitMQ for queue-based async processing and inter-service communication, improving system reliability and performance.",
      "Set up CI/CD pipelines using GitLab, deploying services on AWS EKS (Kubernetes) with automated testing and rollback capabilities.",
      "Implemented comprehensive monitoring using Prometheus + Grafana, and centralized logging via the ELK Stack for better observability.",
      "Collaborated with the AI team to integrate privacy-preserving machine learning models, bridging the gap between traditional backend and AI systems.",
      "Mentored junior developers and participated in architecture planning, sprint cycles, and Agile ceremonies to ensure project success.",
    ],
    skills: [
      "Node.js",
      "Typescript",
      "AWS",
      "Lambda",
      "EKS",
      "Redis",
      "RabbitMQ",
      "PostgreSQL",
      "Prometheus",
      "Grafana",
      "ELK Stack",
      "GitLab CI",
      "Microservices",
      "Event-Driven",
      "Clean Architecture",
    ],
    companyUrl: "https://www.secuvy.ai/",
    logo: "/experience/secuvy/logo.png",
  },  
  {
    id: "leverage-edu",
    position: "Software Developer",
    company: "Leverage Edu",
    location: "Noida, India",
    startDate: new Date("2022-11-01"),
    endDate: new Date("2023-09-01"),
    description: [
      "Designed and implemented a Referral Program, increasing student registration by 35%.",
      "Developed a system that automates incentives and invoices using Redis queues + PostgreSQL transactions.",
      "Optimized SQL queries with indexing strategies, improving lead verification efficiency by 50%.",
      "Handled bulk uploads (200K+ records) daily with efficient pagination and batching.",
      "Built and maintained frontend components using React.js, integrating seamlessly with backend services.",
      "Used Node.js, JavaScript, and PostgreSQL to develop and maintain scalable backend services.",
      "Participated in system architecture discussions and distributed system challenges, contributing scalable design patterns.",
    ],
    achievements: [
      "Designed and implemented a Referral Program that significantly increased student registration by 35%, demonstrating the impact of well-designed backend systems on business outcomes.",
      "Developed a comprehensive system that automates incentives and invoices using Redis queues + PostgreSQL transactions, ensuring data consistency and improving operational efficiency.",
      "Optimized SQL queries with indexing strategies, improving lead verification efficiency by 50% and enhancing overall system performance.",
      "Handled bulk uploads (200K+ records) daily with efficient pagination and batching, ensuring the system could scale to meet growing demands.",
      "Built and maintained frontend components using React.js, integrating seamlessly with backend services to provide a cohesive user experience.",
      "Used Node.js, JavaScript, and PostgreSQL to develop and maintain scalable backend services that supported the company's growth.",
      "Participated in system architecture discussions and distributed system challenges, contributing scalable design patterns and best practices.",
    ],
    skills: [
      "Node.js",
      "Javascript",
      "React.js",
      "PostgreSQL",
      "Redis",
      "SQL",
      "Bulk Processing",
    ],
    companyUrl: "https://leverageedu.com/",
    logo: "/experience/leverage-edu/logo.png",
  },
  {
    id: "infosys",
    position: "Backend Engineer",
    company: "Infosys Ltd.",
    location: "Hyderabad, India",
    startDate: new Date("2021-12-01"),
    endDate: new Date("2022-11-01"),
    description: [
      "Developed RESTful APIs using Java and Spring Boot for enterprise communication tools.",
      "Built an SMS-based alerting system reducing manual work by 80%.",
      "Implemented CI/CD pipelines with Jenkins and Git, reducing manual release errors.",
      "Performed extensive query optimization, speeding up data retrieval by 60% on large employee datasets.",
    ],
    achievements: [
      "Developed RESTful APIs using Java and Spring Boot for enterprise communication tools, ensuring robust and scalable solutions for large organizations.",
      "Built an SMS-based alerting system that reduced manual work by 80%, significantly improving operational efficiency and reducing human error.",
      "Implemented CI/CD pipelines with Jenkins and Git, reducing manual release errors and ensuring consistent deployment processes.",
      "Performed extensive query optimization, speeding up data retrieval by 60% on large employee datasets, demonstrating the importance of database performance tuning.",
      "My work at Infosys provided me with valuable experience in enterprise software development and large-scale system optimization.",
    ],
    skills: [
      "Java",
      "Spring Boot",
      "Jenkins",
      "Git",
      "SQL",
      "RESTful APIs",
      "SMS Integration",
    ],
    companyUrl: "https://www.infosys.com/",
    logo: "/experience/infosys/logo.jpg",
  },
  {
    id: "freelance",
    position: "Software Developer",
    company: "Freelance",
    location: "Remote",
    startDate: new Date("2019-07-01"),
    endDate: new Date("2021-08-01"),
    description: [
      "Built SaaS applications using Node.js + MongoDB + Redis, optimized with caching and rate limiting.",
      "Deployed containerized microservices to AWS (EC2, S3, Lambda) using Terraform and Docker.",
      "Added observability using Prometheus and alerting rules.",
      "Improved performance with SQL indexing and query caching for multi-tenant workloads.",
    ],
    achievements: [
      "Built SaaS applications using Node.js + MongoDB + Redis, optimized with caching and rate limiting to ensure high performance and reliability.",
      "Deployed containerized microservices to AWS (EC2, S3, Lambda) using Terraform and Docker, demonstrating expertise in cloud infrastructure and DevOps practices.",
      "Added observability using Prometheus and alerting rules, ensuring that systems could be monitored effectively and issues could be detected early.",
      "Improved performance with SQL indexing and query caching for multi-tenant workloads, optimizing database operations for better scalability.",
      "This freelance experience allowed me to work on diverse projects and develop a strong foundation in modern backend development practices.",
    ],
    skills: [
      "Node.js",
      "MongoDB",
      "Redis",
      "AWS",
      "EC2",
      "S3",
      "Lambda",
      "Docker",
      "Terraform",
      "Prometheus",
      "SQL",
      "Multi-tenant",
    ],
    logo: "/experience/freelance/logo.png",
  },
];
