export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Go"
  | "Rust"
  | "RabbitMQ"
  | "Kafka"
  | "Prometheus"
  | "Grafana"
  | "ELK Stack"
  | "GitHub Actions"
  | "GitLab CI"
  | "Terraform"
  | "Microservices"
  | "CQRS"
  | "Event-Driven"
  | "Clean Architecture"
  | "n8n"
  | "BullQ"
  | "Lambda"
  | "EKS"
  | "S3"
  | "EC2"
  | "Solana"
  | "Smart Contracts"
  | "NFT"
  | "Web3"
  | "Blockchain"
  | "AI/ML"
  | "OpenAI API"
  | "Machine Learning"
  | "Privacy-Preserving ML"
  | "React.js"
  | "SQL"
  | "Bulk Processing"
  | "RESTful APIs"
  | "SMS Integration"
  | "Multi-tenant"
  | "Cybersecurity"
  | "Security Architecture"
  | "Team Leadership"
  | "Business Development"
  | "QR Code"
  | "Cryptography"
  | "Browser Extension"
  | "Wallet Security"
  | "Fastify"
  | "Document Parsing"
  | "Legal Tech";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "Web3"
  | "AI"
  | "Blockchain"
  | "Cloud";

export type ValidExpType = "Personal Project" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "experience"
  | "career"
  | "contact"
  | "contributions"
  | "resume";
