export const siteConfig = {
  name: "Lokesh Jha | Developer Portfolio",
  authorName: "Lokesh Jha",
  username: "lokesh1jha",
  description:
    "Lokesh Jha's portfolio - A modern, responsive Next.js portfolio for developers. Senior Backend Developer with expertise in blockchain and AI technologies.",
  url: "https://lokeshjha.xyz",
  links: {
    twitter: "https://x.com/Lokesh1jha",
    github: "https://github.com/lokesh1jha",
  },
  ogImage: "https://lokeshjha.xyz/profile-img.jpg",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/lokesh-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/lokesh-logo.png",
  keywords: [
    "Lokesh Jha",
    "Senior Backend Developer",
    "Blockchain Developer",
    "AI Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Backend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
